### **Lấy và làm sạch Dữ liệu AQI và Weather từ AQI**

![Ảnh](./images/pam1_JLLG.png)

#### **I. Import các thư viện**

In [15]:
import requests
import json
import pandas as pd
import numpy as np
import datetime
from datetime import datetime, timedelta
from time import sleep
%matplotlib inline

#### **II. Lấy dữ liệu từ API và tạo Dataframe từ data lấy được**
Trong dự án này, dữ liệu chất lượng không khí được thu thập thông qua [Weatherbit API](https://www.weatherbit.io/), một nền tảng tổng hợp dữ liệu khí tượng – môi trường toàn cầu.Weatherbit không trực tiếp đặt cảm biến tại từng vị trí địa lý, mà tổng hợp dữ liệu từ nhiều nguồn khác nhau, bao gồm:
- Các trạm quan trắc mặt đất (ground-based stations),

- Dữ liệu vệ tinh khí tượng (NASA MODIS, TROPOMI, MOPITT, v.v.),

- Và các mô hình khí tượng – hóa học (numerical models) như WRF-Chem, CAMS, GEOS-Chem.

Dữ liệu sau khi được thu thập sẽ được hiệu chỉnh sai số, nội suy không gian và chuẩn hóa theo từng ô lưới (grid) có kích thước khoảng 10 km × 10 km.
Điều này có nghĩa là các khu vực nằm trong cùng một ô lưới (ví dụ các quận nội thành Hà Nội nằm gần nhau) sẽ nhận được cùng một giá trị AQI và nồng độ các chất ô nhiễm (PM₂.₅, PM₁₀, CO, NO₂, SO₂, O₃).

Vì vậy, để tránh hiện tượng dữ liệu bị trùng lặp (nhân bản) giữa các quận lân cận, dự án lựa chọn tọa độ trung tâm của quận Hoàn Kiếm (21.0285°N, 105.8542°E) làm điểm đại diện cho khu vực nội thành Hà Nội. Hoàn Kiếm là khu vực trung tâm thủ đô, có mật độ dân cư cao, nhiều hoạt động giao thông và thương mại, do đó phản ánh tương đối chính xác chất lượng không khí trung bình của toàn khu vực đô thị Hà Nội.

In [28]:
# API_KEY = "d0abdba555a24c308b658ff1a9af5267"
API_KEY = "edb2db4cc2b84bec8a09cc37173ca0cc"
LAT, LON = 21.0285, 105.8542

start_date = datetime(2023, 1, 1)
end_date = datetime(2025, 1, 1, 0)

urls_air = []
urls_wea = []
current = start_date
while current < end_date:
    next_month = (current.replace(day=28) + timedelta(days=4)).replace(day=1)
    start_str = current.strftime('%Y-%m-%d')
    end_str = next_month.strftime('%Y-%m-%d')
    
    url_air = f"https://api.weatherbit.io/v2.0/history/airquality?lat={LAT}&lon={LON}&start_date={start_str}&end_date={end_str}&tz=local&key={API_KEY}"
    url_wea = f"https://api.weatherbit.io/v2.0/history/hourly?lat={LAT}&lon={LON}&start_date={start_str}&end_date={end_str}&tz=local&key={API_KEY}"
    urls_air.append(url_air)
    urls_wea.append(url_wea)
    current = next_month

print(f" Tạo{len(urls_air)} URLs ({urls_air[0]} → {urls_air[-1]})")
print(f" Tạo{len(urls_wea)} URLs ({urls_wea[0]} → {urls_wea[-1]})")

 Tạo24 URLs (https://api.weatherbit.io/v2.0/history/airquality?lat=21.0285&lon=105.8542&start_date=2023-01-01&end_date=2023-02-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc → https://api.weatherbit.io/v2.0/history/airquality?lat=21.0285&lon=105.8542&start_date=2024-12-01&end_date=2025-01-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc)
 Tạo24 URLs (https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-01-01&end_date=2023-02-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc → https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-12-01&end_date=2025-01-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc)

##### **2.1 AIR QUALITY**

In [ ]:
# results_air = []
# for i, url in enumerate(urls_air):
#     print(f'Lấy dữ liệu từ URL {i}/{len(urls_air)} : {url}')
#     try:
#         renponse = requests.get(url, timeout=30)
#         renponse.raise_for_status()
#         data = json.loads(renponse.text)
#         results_air.append(data)
#         sleep(1.2)
        
#     except Exception as e:
#         print(f"Lỗi khi lấy dữ liệu {i} : {e}")
        
# print(f"\n Hoàn tất tải {len(results_air)} ")

In [ ]:
# results_air[0]['city_name']

In [ ]:


# results_air[0]['data'][0]

In [ ]:
# joined_data = []
# for res in results_air:
#     if 'data' in res:
#         joined_data.extend(res['data'])
        
# joined_results = {
#     'city_name': results_air[0]['city_name'],
#     'country_code': results_air[0]['country_code'],
#     'lat': results_air[0]['lat'],
#     'lon': results_air[0]['lon'],
#     'timezone': results_air[0]['timezone'],
#     'data': joined_data
# }

NameError: name 'results_air' is not defined

In [ ]:
# joined_results['data'][0]

In [ ]:
# joined_results['data'][-1]

In [ ]:

# df = pd.DataFrame(joined_results)

# df.columns = ['City', 'Country code', 'Lat', 'Lon', 'timezone', 'Data']
# df[['AQI', 'CO', 'Date Time', 'NO2', 'O3', 'PM10', 'PM25', 'SO2', 'Local Time', 'UTC Time', 'TS']] = pd.DataFrame(df['Data'].tolist())
# df.drop(columns=['Data', 'Lat', 'Lon', 'TS', 'Date Time'], inplace=True)
# df = df.drop_duplicates()
# df = df.sort_values(by='Local Time')
# df['Local Time'] = pd.to_datetime(df['Local Time'])
# df.set_index('Local Time', inplace=True)
# df.head()

NameError: name 'joined_results' is not defined

In [35]:
# df.to_csv('air_quality_data.csv', index=True)

In [41]:
df = pd.read_csv('air_quality_data_1.csv')
df.shape

(17549, 12)

##### **2.2 WEATHER**

In [29]:
results_wea = []
for i, url in enumerate(urls_wea):
    print(f'Lấy dữ liệu từ URL {i}/{len(urls_wea)} : {url}')
    try:
        renponse = requests.get(url, timeout=30)
        renponse.raise_for_status()
        data = json.loads(renponse.text)
        results_wea.append(data)
        sleep(1.2)
        
    except Exception as e:
        print(f"Lỗi khi lấy dữ liệu {i} : {e}")
        
print(f"\n Hoàn tất tải {len(results_wea)} ")

Lấy dữ liệu từ URL 0/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-01-01&end_date=2023-02-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 1/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-02-01&end_date=2023-03-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 1 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-02-01&end_date=2023-03-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 2/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-03-01&end_date=2023-04-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 2 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-03-01&end_date=2023-04-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 3/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-04-01&end_date=2023-05-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 3 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-04-01&end_date=2023-05-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 4/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-05-01&end_date=2023-06-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 4 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-05-01&end_date=2023-06-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 5/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-06-01&end_date=2023-07-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 5 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-06-01&end_date=2023-07-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 6/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-07-01&end_date=2023-08-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 6 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-07-01&end_date=2023-08-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 7/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-08-01&end_date=2023-09-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 7 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-08-01&end_date=2023-09-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 8/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-09-01&end_date=2023-10-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 8 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-09-01&end_date=2023-10-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 9/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-10-01&end_date=2023-11-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 9 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-10-01&end_date=2023-11-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 10/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-11-01&end_date=2023-12-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 10 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-11-01&end_date=2023-12-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 11/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-12-01&end_date=2024-01-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 11 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2023-12-01&end_date=2024-01-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 12/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-01-01&end_date=2024-02-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 12 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-01-01&end_date=2024-02-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 13/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-02-01&end_date=2024-03-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 13 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-02-01&end_date=2024-03-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 14/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-03-01&end_date=2024-04-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 14 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-03-01&end_date=2024-04-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 15/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-04-01&end_date=2024-05-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 15 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-04-01&end_date=2024-05-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 16/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-05-01&end_date=2024-06-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lỗi khi lấy dữ liệu 16 : 429 Client Error: Too Many Requests for url: https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-05-01&end_date=2024-06-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc
Lấy dữ liệu từ URL 17/24 : https://api.weatherbit.io/v2.0/history/hourly?lat=21.0285&lon=105.8542&start_date=2024-06-01&end_date=2024-07-01&tz=local&key=edb2db4cc2b84bec8a09cc37173ca0cc

KeyboardInterrupt:

In [26]:
joined_data = []
for res in results_wea:
    if 'data' in res:
        joined_data.extend(res['data'])
        
joined_results_weather = {
    'city_name': results_wea[0]['city_name'],
    'country_code': results_wea[0]['country_code'],
    'lat': results_wea[0]['lat'],
    'lon': results_wea[0]['lon'],
    'timezone': results_wea[0]['timezone'],
    'data': joined_data
}

In [32]:

df_weather = pd.DataFrame(joined_results_weather)


df_weather.columns = ['City', 'Country code', 'Lat', 'Lon', 'timezone', 'Data']

d = pd.json_normalize(df_weather.pop('Data'))

keep = d[["clouds","precip","pres","rh","temp","uv","wind_spd","timestamp_local","timestamp_utc"]].rename(columns={
    "clouds":"Clouds",
    "precip":"Precipitation",
    "pres":"Pressure",
    "rh":"Relative Humidity",
    "temp":"Temperature",
    "uv":"UV Index",
    "wind_spd":"Wind Speed",
    "timestamp_local":"Local Time",
    "timestamp_utc":"UTC Time"
})
df_weather = pd.concat([df_weather[['City', 'Country code', 'timezone']], keep], axis=1)

df_weather.head()

,City,Country code,timezone,Clouds,Precipitation,Pressure,Relative Humidity,Temperature,UV Index,Wind Speed,Local Time,UTC Time
0,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,87,0.0,1024,73,14.8,0.0,0.66,2023-01-01T00:00:00,2022-12-31T17:00:00
1,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,87,0.0,1023,75,14.6,0.0,1.00,2023-01-01T01:00:00,2022-12-31T18:00:00
2,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,83,0.0,1023,79,14.3,0.0,1.00,2023-01-01T02:00:00,2022-12-31T19:00:00
3,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,79,0.0,1023,82,14.1,0.0,1.00,2023-01-01T03:00:00,2022-12-31T20:00:00
4,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,75,0.0,1022,86,13.8,0.0,1.00,2023-01-01T04:00:00,2022-12-31T21:00:00

In [33]:
df_weather.to_csv('weather_data.csv', index=False)

In [ ]:
# df_weather[['Apparent Temperature', 'Azimuth', 'Clouds', 'Datetime', 'Dew Point', 'DHI', 'DNI', 'Elevation Angle', 'GHI',
#             'H Angle', 'Pod', 'Precipitation', 'Pressure', 'Status', 'Relative Humidity', 'Sea Level Pressure', 'Snow',
#             'Solar Radiation', 'Temperature', 'Local Time', 'UTC Time', 'Timestamp', 'UV Index', 'Visibility', 'Weather',
#             'Wind Direction', 'Wind Gust Speed', 'Wind Speed']] = pd.DataFrame(df_weather['Data'].tolist())


# df_weather.drop(columns=['Data', 'Lat', 'Lon', 'Apparent Temperature', 'Azimuth','Datetime', 'Dew Point', 'DHI', 'DNI',
#                          'Elevation Angle', 'GHI', 'H Angle', 'Pod', 'Status', 'Sea Level Pressure', 'Snow',
#                          'Solar Radiation', 'Timestamp', 'Visibility', 'Wind Direction', 'Wind Gust Speed', 'Weather'], inplace=True)


# df_weather = df_weather.drop_duplicates()


# df_weather = df_weather.sort_values(by='Local Time')


# df_weather['Local Time'] = pd.to_datetime(df_weather['Local Time'])

# df_weather.set_index('Local Time', inplace=True)


# df_weather = df_weather[:-23]

# df_weather

In [34]:

df_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               17544 non-null  object
 1   Country code       17544 non-null  object
 2   timezone           17544 non-null  object
 3   Clouds             17544 non-null  int64
 4   Precipitation      17544 non-null  float64
 5   Pressure           17544 non-null  int64
 6   Relative Humidity  17544 non-null  int64
 7   Temperature        17544 non-null  float64
 8   UV Index           17544 non-null  float64
 9   Wind Speed         17544 non-null  float64
 10  Local Time         17544 non-null  object
 11  UTC Time           17544 non-null  object
dtypes: float64(4), int64(3), object(5)
memory usage: 1.6+ MB


#### **IV. Hợp nhất hai khung dữ liệu và sắp xếp dữ liệu**

In [44]:

merged_df = pd.merge(df, df_weather, left_index=True, right_index=True)

merged_df.drop(columns=['City_y', 'Country code_y', 'timezone_y', 'UTC Time_y'], inplace=True)

utc_time_column = merged_df.pop('UTC Time_x')
merged_df.insert(0, 'UTC Time', utc_time_column)

merged_df = merged_df.rename(columns={'City_x': 'City', 'Country code_x': 'Country Code', 'timezone_x':'Timezone'})
merged_df

,UTC Time,Local Time_x,City,Country Code,Timezone,AQI,CO,NO2,O3,PM10,PM25,SO2,Clouds,Precipitation,Pressure,Relative Humidity,Temperature,UV Index,Wind Speed,Local Time_y
0,2022-12-31T17:00:00,1/1/2023 0:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,155,224.5,9.0,55.7,73.8,59.00,62.3,87,0.0,1024,73,14.8,0.0,0.66,2023-01-01T00:00:00
1,2022-12-31T18:00:00,1/1/2023 1:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,171,206.0,6.0,56.0,88.8,71.00,59.0,87,0.0,1023,75,14.6,0.0,1.00,2023-01-01T01:00:00
2,2022-12-31T19:00:00,1/1/2023 2:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,179,203.7,6.0,54.0,96.3,77.00,58.0,83,0.0,1023,79,14.3,0.0,1.00,2023-01-01T02:00:00
3,2022-12-31T20:00:00,1/1/2023 3:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,199,201.3,6.0,52.0,115.0,92.00,57.0,79,0.0,1023,82,14.1,0.0,1.00,2023-01-01T03:00:00
4,2022-12-31T21:00:00,1/1/2023 4:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,161,199.0,6.0,50.0,80.0,64.00,56.0,75,0.0,1022,86,13.8,0.0,1.00,2023-01-01T04:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17539,2024-12-31T08:00:00,12/31/2024 15:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,173,605.0,15.0,27.0,100.0,73.00,26.0,37,0.0,1018,82,16.8,0.0,2.00,2024-12-31T19:00:00
17540,2024-12-31T09:00:00,12/31/2024 16:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,165,806.0,8.0,15.1,94.0,67.00,26.0,1,0.0,1018,86,16.0,0.0,2.00,2024-12-31T20:00:00
17541,2024-12-31T10:00:00,12/31/2024 17:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,183,1310.0,10.3,10.8,108.0,80.33,28.0,0,0.0,1018,90,15.2,0.0,2.00,2024-12-31T21:00:00
17542,2024-12-31T11:00:00,12/31/2024 18:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,168,1109.0,15.0,10.8,96.0,69.00,32.0,1,0.0,1019,94,14.4,0.0,1.60,2024-12-31T22:00:00
17543,2024-12-31T12:00:00,12/31/2024 19:00,Hoàn Kiếm,VN,Asia/Ho_Chi_Minh,219,2318.0,15.0,2.2,136.0,107.00,32.0,2,0.0,1018,94,14.0,0.0,2.00,2024-12-31T23:00:00

In [52]:

merged_df.shape

(17544, 19)

In [57]:
merged_df.rename(columns={'Local Time_x': 'Local Time'}, inplace=True)
# merged_df = merged_df[['Local Time', 'UTC Time', 'City', 'Country Code', 'Timezone', 'AQI', 'CO', 'NO2', 'O3', 'PM10', 'PM25', 'SO2',
#                        'Clouds', 'Precipitation', 'Pressure', 'Relative Humidity', 'Temperature', 'UV Index', 'Wind Speed']]

merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17544 entries, 0 to 17543
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   UTC Time           17544 non-null  object
 1   Local Time         17544 non-null  object
 2   City               17544 non-null  object
 3   Country Code       17544 non-null  object
 4   Timezone           17544 non-null  object
 5   AQI                17544 non-null  int64
 6   CO                 17544 non-null  float64
 7   NO2                17544 non-null  float64
 8   O3                 17544 non-null  float64
 9   PM10               17544 non-null  float64
 10  PM25               17544 non-null  float64
 11  SO2                17544 non-null  float64
 12  Clouds             17544 non-null  int64
 13  Precipitation      17544 non-null  float64
 14  Pressure           17544 non-null  int64
 15  Relative Humidity  17544 non-null  int64
 16  Temperature        17544 non-null  float64
 17  UV Index           17544 non-null  float64
 18  Wind Speed         17544 non-null  float64
dtypes: float64(10), int64(4), object(5)
memory usage: 2.7+ MB

In [59]:

merged_df.to_csv('hanoi-aqi-weather-data.csv', index=False)